version: '3'

services: 

  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install express --save && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    build:
      context: db
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    #environment: 
    #  - MYSQL_DATABASE=nodedb
    #  - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
